#!/usr/bin/env python3 
from urllib import request
import re
import argparse
import itertools

if __name__ == '__main__':

	parser = argparse.ArgumentParser(add_help = False)

	parser.add_argument("-input",  dest = 'input')
	parser.add_argument("-output", dest = 'output')
	args = parser.parse_args()

	input_file = open(args.input, 'r')
	input_text = input_file.read().replace('(', '( ')
	input_text = input_text.replace(')', ' )')
	sentences = re.split("\n\n", input_text) 

	splitted_sentences = sentences

	niveau = []
	output_sentence = []
	output_string = ''

	for i in range(1):
		splitted_sentences[i] = re.split("\s", sentences[i])
		current_sentence = splitted_sentences[i]
		j = 0
		while(j < len(current_sentence)):
		# for j in range(len(current_sentence)):
			output_string = output_string + ' ' + current_sentence[j]
			# output_sentence.append(output_string)
			if(current_sentence[j] == '('):
				niveau.append(current_sentence[j+1])
				if((current_sentence[j+2] == '(') and (current_sentence[j+1] != 'ROOT')):
					output_string = output_string + niveau[-1] + '^' + niveau[-2] + ' '
					# output_sentence.append(output_string)
					j += 1
					# print(j)
				# print(niveau)
			elif(current_sentence[j] == ')'):
				del niveau[-1]
			j += 1	
				# print(niveau)	
			print(output_string)		